var historyTransactions = [
  {
    id: 'TX-483920',
    entity: 'Pacific Ridge Financial',
    entityType: 'Business',
    experience: 'Business Reputation Review',
    experienceType: 'Risk Intelligence',
    outcome: 'Low Risk',
    status: 'Completed',
    kybSample: 'standard',
    availability: 'live',
    started: '2026-07-31T07:30:00',
    lastUpdated: '2026-07-31T09:00:00',
    lastUpdatedLabel: '2 hours ago',
    startedLabel: 'Jul 31, 2026 · 7:30 AM',
    aiSummary: 'Reputation screening returned no sanctions hits. Adverse media review identified one neutral industry mention. Overall risk posture assessed as low based on verified registration and clean watchlist results.',
  },
  {
    id: 'TX-483911',
    entity: 'Acme Logistics Ltd.',
    entityType: 'Business',
    experience: 'Cross-Border Ownership Investigation',
    experienceType: 'Ownership',
    outcome: '2 UBOs Identified',
    status: 'In Progress',
    kybSample: 'complex',
    availability: 'demo',
    started: '2026-07-30T14:15:00',
    lastUpdated: '2026-07-30T18:40:00',
    lastUpdatedLabel: 'Yesterday',
    startedLabel: 'Jul 30, 2026 · 2:15 PM',
    aiSummary: 'Ownership tracing identified two ultimate beneficial owners across UK and Netherlands entities. One intermediate holding layer requires additional registry confirmation before the investigation can be finalized.',
  },
  {
    id: 'TX-483884',
    entity: 'John Smith',
    entityType: 'Person',
    experience: 'Digital Identity Onboarding',
    experienceType: 'Verification',
    outcome: 'Verified',
    status: 'Completed',
    availability: 'live',
    started: '2026-07-28T10:05:00',
    lastUpdated: '2026-07-28T10:22:00',
    lastUpdatedLabel: 'Jul 28',
    startedLabel: 'Jul 28, 2026 · 10:05 AM',
    aiSummary: 'Digital identity provider returned a high-confidence match. Document authenticity checks passed and the customer profile was verified without manual review.',
  },
  {
    id: 'TX-483871',
    entity: 'Meridian Apex',
    entityType: 'Business',
    experience: 'Customer Onboarding Policy Review',
    experienceType: 'Policy Review',
    outcome: 'Review Required',
    status: 'Completed',
    kybSample: 'standard',
    availability: 'demo',
    started: '2026-07-27T09:00:00',
    lastUpdated: '2026-07-27T11:45:00',
    lastUpdatedLabel: 'Jul 27',
    startedLabel: 'Jul 27, 2026 · 9:00 AM',
    aiSummary: 'Policy review flagged two onboarding requirements that differ from the current KYB playbook. AI recommended updates to beneficial ownership documentation before approval.',
  },
  {
    id: 'TX-483860',
    entity: 'Blue River Capital',
    entityType: 'Business',
    experience: 'Deep Business Investigation',
    experienceType: 'Research',
    outcome: 'AI Report Generated',
    status: 'Completed',
    kybSample: 'elevated',
    availability: 'demo',
    started: '2026-07-26T08:30:00',
    lastUpdated: '2026-07-26T13:10:00',
    lastUpdatedLabel: 'Jul 26',
    startedLabel: 'Jul 26, 2026 · 8:30 AM',
    aiSummary: 'Deep research synthesized registry filings, web intelligence, and verification signals into a structured AI report. Key findings include stable operating history and no elevated media risk.',
  },
  {
    id: 'TX-483842',
    entity: 'Northwind Payments',
    entityType: 'Business',
    experience: 'Ongoing Business Monitoring',
    experienceType: 'Monitoring',
    outcome: 'Monitoring Active',
    status: 'Monitoring',
    kybSample: 'standard',
    availability: 'live',
    started: '2026-07-25T07:00:00',
    lastUpdated: '2026-07-31T06:00:00',
    lastUpdatedLabel: '4 hours ago',
    startedLabel: 'Jul 25, 2026 · 7:00 AM',
    aiSummary: 'Continuous monitoring is active for registration, ownership, and sanctions changes. No material alerts have been detected in the latest monitoring cycle.',
  },
  {
    id: 'TX-483831',
    entity: 'Harbor Document Services',
    entityType: 'Document',
    experience: 'Document Verification',
    experienceType: 'Verification',
    outcome: 'Manual Review Required',
    status: 'Failed',
    availability: 'live',
    started: '2026-07-24T16:20:00',
    lastUpdated: '2026-07-24T17:05:00',
    lastUpdatedLabel: 'Jul 24',
    startedLabel: 'Jul 24, 2026 · 4:20 PM',
    aiSummary: 'Document authenticity checks detected potential tampering on the submitted passport image. The transaction failed automated verification and was routed for manual review.',
  },
  {
    id: 'TX-483819',
    entity: 'Mobile Session 44A9',
    entityType: 'Device',
    experience: 'Identity and Device Risk Assessment',
    experienceType: 'Risk Intelligence',
    outcome: 'Elevated Device Risk',
    status: 'Completed',
    availability: 'live',
    started: '2026-07-23T12:00:00',
    lastUpdated: '2026-07-23T12:18:00',
    lastUpdatedLabel: 'Jul 23',
    startedLabel: 'Jul 23, 2026 · 12:00 PM',
    aiSummary: 'Identity verification succeeded, but device intelligence flagged an unfamiliar network pattern and emulator-like signals. Risk was elevated and logged for analyst review.',
  },
  {
    id: 'TX-483802',
    entity: 'Operating Account ·••4821',
    entityType: 'Bank Account',
    experience: 'Business Account Verification',
    experienceType: 'Verification',
    outcome: 'Account Verified',
    status: 'Completed',
    availability: 'live',
    started: '2026-07-22T09:45:00',
    lastUpdated: '2026-07-22T10:05:00',
    lastUpdatedLabel: 'Jul 22',
    startedLabel: 'Jul 22, 2026 · 9:45 AM',
    aiSummary: 'Bank account ownership was confirmed through account verification signals. The linked account matches the onboarding business profile with high confidence.',
  },
  {
    id: 'TX-483790',
    entity: 'Trulioo MCP Agent',
    entityType: 'Business',
    experience: 'Trulioo MCP Agent',
    experienceType: 'Research',
    outcome: 'External Session Started',
    status: 'In Progress',
    kybSample: 'standard',
    availability: 'external',
    started: '2026-07-31T08:45:00',
    lastUpdated: '2026-07-31T09:30:00',
    lastUpdatedLabel: '1 hour ago',
    startedLabel: 'Jul 31, 2026 · 8:45 AM',
    aiSummary: 'An external AI assistant initiated an MCP session to query Trulioo intelligence APIs. Session activity is in progress and results will sync when the external workflow completes.',
  },
];

var historyFilterGroups = {
  entity: ['Business', 'Person', 'Document', 'Device', 'Bank Account'],
  experience: ['Verification', 'Risk Intelligence', 'Ownership', 'Research', 'Monitoring', 'Policy Review'],
  status: ['Completed', 'In Progress', 'Monitoring', 'Failed'],
  date: [
    { id: 'today', label: 'Today' },
    { id: 'last7', label: 'Last 7 days' },
    { id: 'last30', label: 'Last 30 days' },
    { id: 'custom', label: 'Custom Range' },
  ],
  availability: [
    { id: 'live', label: 'Live', dot: 'live' },
    { id: 'demo', label: 'Demo', dot: 'demo' },
    { id: 'external', label: 'External', dot: 'external' },
  ],
};

var historySortOptions = [
  { id: 'lastUpdated', label: 'Last Updated' },
  { id: 'started', label: 'Started Date' },
  { id: 'id', label: 'Transaction ID' },
  { id: 'entity', label: 'Entity Name' },
  { id: 'status', label: 'Status' },
];

function resolvePageUrl(relativeUrl, githubUrl) {
  if (typeof window === 'undefined') return githubUrl;
  if (window.location.protocol === 'file:') return relativeUrl;

  try {
    return new URL(relativeUrl, window.location.href).href;
  } catch (e) {
    return githubUrl;
  }
}

var kybResultsUrl = resolvePageUrl(
  'kyb-results.html',
  'https://zoeychun.github.io/trulioo-labs-design-system/pages/unified-intelligence-home/kyb-results.html'
);
