var labsExperiences = [
  {
    id: 'document-verification',
    title: 'KYC Documents',
    description: 'Verify passports and identity documents using AI-assisted authenticity checks.',
    experienceType: 'live',
    useCase: 'KYC',
    industry: 'Travel',
    icon: 'document-verification',
    tags: ['KYC'],
    featured: true,
    order: 1,
    url: 'document-verification-transactions.html',
    preview: 'assets/labs-preview-document-verification.png',
  },
  {
    id: 'bank-verification',
    title: 'Bank Verification',
    description: 'Verify ownership of a personal or business bank account during onboarding.',
    experienceType: 'live',
    useCase: 'KYC',
    industry: 'Finance',
    icon: 'bank-verification',
    tags: ['KYB', 'KYC'],
    featured: true,
    order: 2,
    url: '../bank-verification/index.html',
    preview: 'assets/labs-preview-bank-verification.png',
  },
  {
    id: 'electronic-id',
    title: 'Electronic ID',
    description: 'Verify a customer using a trusted digital identity provider instead of uploading physical documents.',
    experienceType: 'live',
    useCase: 'KYC',
    industry: 'Travel',
    icon: 'electronic-id',
    tags: ['KYC'],
    featured: true,
    order: 3,
    url: '../electronic-id/index.html',
    preview: 'assets/labs-preview-electronic-id.png',
  },
  {
    id: 'kyc-eidas',
    title: 'eIDAS compliant KYC',
    description: 'Complete eIDAS 2.0 identity verification across Europe with a national eID or document.',
    experienceType: 'live',
    useCase: 'KYC',
    industry: 'Finance',
    icon: 'kyc-eidas',
    tags: ['KYC'],
    featured: true,
    order: 4,
    url: '../KYC eIDAS/index.html',
    preview: 'assets/labs-preview-kyc-eidas.png',
  },
  {
    id: 'device-intelligence',
    title: 'Device Intelligence',
    description: 'Discover device attributes, environment details, and signals that may indicate risky behaviour.',
    experienceType: 'live',
    useCase: 'KYC',
    industry: 'Gaming',
    icon: 'device-intelligence',
    tags: ['KYC'],
    featured: true,
    order: 5,
    url: '../device-intelligence/index.html',
    preview: 'assets/labs-preview-device-intelligence.png',
  },
  {
    id: 'business-reputation-review',
    title: 'Business Horizon',
    description: 'Assess business horizon using sanctions, adverse media, and web intelligence.',
    experienceType: 'demo',
    useCase: 'KYB',
    industry: 'Marketplace',
    icon: 'business-reputation-review',
    tags: ['KYB'],
    badge: 'demo',
    external: true,
    featured: true,
    order: 6,
    url: '../business-reputation-review/index.html',
    preview: 'assets/labs-preview-kyb-results.png',
  },
  {
    id: 'trulioo-mcp-agent',
    title: 'Orchestration Agent',
    description: 'Connect Trulioo intelligence with external AI assistants through the Model Context Protocol (MCP).',
    experienceType: 'external',
    useCase: 'KYB',
    industry: 'Digital Assets',
    icon: 'trulioo-mcp-agent',
    tags: ['KYB', 'KYC'],
    badge: 'external',
    external: true,
    featured: false,
    order: 7,
    url: '',
  },
  {
    id: 'ubo-agent',
    title: 'UBO Agent',
    description: 'Map ultimate beneficial owners and relationship networks across entities and jurisdictions.',
    experienceType: 'live',
    useCase: 'KYB',
    industry: 'Marketplace',
    icon: 'ubo-agent',
    tags: ['KYB'],
    featured: false,
    order: 8,
  },
  {
    id: 'policy-review',
    title: 'Policy Review',
    description: 'Review onboarding policies and compliance requirements using AI.',
    experienceType: 'live',
    useCase: 'KYB',
    industry: 'Finance',
    icon: 'policy-review',
    tags: ['KYB'],
    featured: false,
    order: 9,
    url: '',
  },
  {
    id: 'deep-search',
    title: 'Deep Search',
    description: 'Generate AI-powered business research using verification signals and public intelligence.',
    experienceType: 'live',
    useCase: 'KYB',
    industry: 'Finance',
    icon: 'deep-search',
    tags: ['KYB'],
    featured: false,
    order: 10,
    url: '',
  },
  {
    id: 'kyb-self-serve',
    title: 'KYB Self-Serve',
    description: 'Verify businesses quickly with a simple, self-serve KYB workflow.',
    experienceType: 'live',
    useCase: 'KYB',
    industry: 'Marketplace',
    icon: 'kyb-self-serve',
    tags: ['KYB'],
    featured: false,
    order: 11,
    url: '',
  },
];

var labsFilterGroups = {
  experienceType: [
    { id: 'live', label: 'Live data' },
    { id: 'demo', label: 'Demo flows' },
    { id: 'external', label: 'External' },
  ],
  useCase: ['KYB', 'KYC'],
};
