var labsExperiences = [
  {
    id: 'business-reputation-review',
    title: 'Business Reputation Review',
    description: 'Assess business reputation using sanctions, adverse media, and web intelligence.',
    experienceType: 'live',
    useCase: 'KYB',
    industry: 'Marketplace',
    featured: true,
    order: 3,
    url: 'index.html',
    preview: 'assets/labs-preview-home.png',
  },
  {
    id: 'customer-onboarding-policy-review',
    title: 'Customer Onboarding Policy Review',
    description: 'Review onboarding policies and compliance requirements using AI.',
    experienceType: 'demo',
    useCase: 'KYB',
    industry: 'Finance',
    featured: true,
    order: 7,
    url: '',
  },
  {
    id: 'deep-business-investigation',
    title: 'Deep Business Investigation',
    description: 'Generate AI-powered business research using verification signals and public intelligence.',
    experienceType: 'demo',
    useCase: 'KYB',
    industry: 'Finance',
    featured: false,
    order: 8,
    url: 'index.html',
  },
  {
    id: 'us-payments-company-onboarding',
    title: 'US Payments Company Onboarding',
    description: 'Verify a newly onboarded payments company using registration, ownership, and risk intelligence.',
    experienceType: 'demo',
    useCase: 'KYB',
    industry: 'Finance',
    featured: false,
    order: 1,
    url: 'index.html',
  },
  {
    id: 'cross-border-ownership-investigation',
    title: 'Cross-Border Ownership Investigation',
    description: 'Investigate complex ownership structures across multiple jurisdictions.',
    experienceType: 'demo',
    useCase: 'KYB',
    industry: 'Marketplace',
    featured: false,
    order: 2,
    url: '../Experiments/ubo-graph/index.html',
  },
  {
    id: 'business-credit-assessment',
    title: 'Business Credit Assessment',
    description: 'Evaluate business creditworthiness before approving financing or merchant services.',
    experienceType: 'live',
    useCase: 'KYB',
    industry: 'Finance',
    featured: false,
    order: 4,
    url: '',
  },
  {
    id: 'business-account-verification',
    title: 'Business Account Verification',
    description: 'Verify ownership of a business bank account during onboarding.',
    experienceType: 'live',
    useCase: 'KYB',
    industry: 'Finance',
    featured: false,
    order: 5,
    url: '../bank-verification/index.html',
  },
  {
    id: 'ongoing-business-monitoring',
    title: 'Ongoing Business Monitoring',
    description: 'Monitor ownership, registration, and regulatory changes after onboarding.',
    experienceType: 'live',
    useCase: 'KYB',
    industry: 'Healthcare',
    featured: false,
    order: 6,
    url: '',
  },
  {
    id: 'customer-onboarding-digital-identity',
    title: 'Customer Onboarding with Digital Identity',
    description: 'Verify a customer using a trusted digital identity provider instead of uploading physical documents.',
    experienceType: 'live',
    useCase: 'KYC',
    industry: 'Travel',
    featured: false,
    order: 9,
    url: '../electronic-id/index.html',
  },
  {
    id: 'passport-verification',
    title: 'Document Verification',
    description: 'Verify passports and identity documents using AI-assisted authenticity checks.',
    experienceType: 'live',
    useCase: 'KYC',
    industry: 'Travel',
    featured: false,
    order: 10,
    url: '../document-verification/index.html',
  },
  {
    id: 'personal-bank-account-verification',
    title: 'Personal Bank Account Verification',
    description: "Confirm ownership of a customer's bank account during onboarding.",
    experienceType: 'live',
    useCase: 'KYC',
    industry: 'Finance',
    featured: false,
    order: 11,
    url: '../bank-verification/index.html',
  },
  {
    id: 'identity-device-risk-assessment',
    title: 'Device Intelligence',
    description: 'Evaluate a device for attributes, environment, and risk signals before approval.',
    experienceType: 'live',
    useCase: 'Fraud',
    industry: 'Gaming',
    featured: true,
    order: 6,
    url: '../device-intelligence/index.html',
    preview: 'assets/labs-preview-device-intelligence.png',
  },
  {
    id: 'trulioo-mcp-agent',
    title: 'Trulioo MCP Agent',
    description: 'Connect Trulioo intelligence with external AI assistants through the Model Context Protocol (MCP).',
    experienceType: 'experiment',
    useCase: 'KYB',
    industry: 'Digital Assets',
    featured: false,
    order: 13,
    url: 'index.html#mcpSection',
  },
];

var labsFilterGroups = {
  experienceType: [
    { id: 'live', label: 'Live data' },
    { id: 'demo', label: 'Demo flows' },
    { id: 'experiment', label: 'External' },
  ],
  useCase: ['KYB', 'KYC', 'Fraud'],
  industry: ['Finance', 'Marketplace', 'Gaming', 'Travel', 'Healthcare', 'Digital Assets'],
};
