var labsExperiences = [
  {
    id: 'business-reputation-review',
    title: 'Business Reputation Review',
    description: 'Assess business reputation using sanctions, adverse media, and web intelligence.',
    entity: 'Business',
    capability: 'Risk Intelligence',
    availability: 'live',
    featured: true,
    order: 3,
    url: 'index.html',
  },
  {
    id: 'customer-onboarding-policy-review',
    title: 'Customer Onboarding Policy Review',
    description: 'Review onboarding policies and compliance requirements using AI.',
    entity: 'Business',
    capability: 'Policy Review',
    availability: 'demo',
    featured: true,
    order: 7,
    url: '#',
  },
  {
    id: 'deep-business-investigation',
    title: 'Deep Business Investigation',
    description: 'Generate AI-powered business research using verification signals and public intelligence.',
    entity: 'Business',
    capability: 'Research',
    availability: 'demo',
    featured: true,
    order: 8,
    url: 'index.html',
  },
  {
    id: 'us-payments-company-onboarding',
    title: 'US Payments Company Onboarding',
    description: 'Verify a newly onboarded payments company using registration, ownership, and risk intelligence.',
    entity: 'Business',
    capability: 'Verification',
    availability: 'demo',
    featured: false,
    order: 1,
    url: 'index.html',
  },
  {
    id: 'cross-border-ownership-investigation',
    title: 'Cross-Border Ownership Investigation',
    description: 'Investigate complex ownership structures across multiple jurisdictions.',
    entity: 'Business',
    capability: 'Ownership',
    availability: 'demo',
    featured: false,
    order: 2,
    url: 'index.html',
  },
  {
    id: 'business-credit-assessment',
    title: 'Business Credit Assessment',
    description: 'Evaluate business creditworthiness before approving financing or merchant services.',
    entity: 'Business',
    capability: 'Verification',
    availability: 'live',
    featured: false,
    order: 4,
    url: '#',
  },
  {
    id: 'business-account-verification',
    title: 'Business Account Verification',
    description: 'Verify ownership of a business bank account during onboarding.',
    entity: 'Bank Account',
    capability: 'Verification',
    availability: 'live',
    featured: false,
    order: 5,
    url: '#',
  },
  {
    id: 'ongoing-business-monitoring',
    title: 'Ongoing Business Monitoring',
    description: 'Monitor ownership, registration, and regulatory changes after onboarding.',
    entity: 'Business',
    capability: 'Monitoring',
    availability: 'live',
    featured: false,
    order: 6,
    url: '#',
  },
  {
    id: 'customer-onboarding-digital-identity',
    title: 'Customer Onboarding with Digital Identity',
    description: 'Verify a customer using a trusted digital identity provider instead of uploading physical documents.',
    entity: 'Person',
    capability: 'Verification',
    availability: 'live',
    featured: false,
    order: 9,
    url: '#',
  },
  {
    id: 'passport-verification',
    title: 'Document Verification',
    description: 'Verify passports and identity documents using AI-assisted authenticity checks.',
    entity: 'Document',
    capability: 'Verification',
    availability: 'live',
    featured: false,
    order: 10,
    url: '#',
  },
  {
    id: 'personal-bank-account-verification',
    title: 'Personal Bank Account Verification',
    description: "Confirm ownership of a customer's bank account during onboarding.",
    entity: 'Bank Account',
    capability: 'Verification',
    availability: 'live',
    featured: false,
    order: 11,
    url: '#',
  },
  {
    id: 'identity-device-risk-assessment',
    title: 'Identity and Device Risk Assessment',
    description: 'Evaluate identity together with device and network intelligence before approval.',
    entity: 'Device',
    capability: 'Risk Intelligence',
    availability: 'live',
    featured: false,
    order: 12,
    url: '#',
  },
  {
    id: 'trulioo-mcp-agent',
    title: 'Trulioo MCP Agent',
    description: 'Connect Trulioo intelligence with external AI assistants through the Model Context Protocol (MCP).',
    entity: 'Business',
    capability: 'Research',
    availability: 'external',
    featured: false,
    order: 13,
    url: '#',
  },
];

var labsFilterGroups = {
  entity: ['Business', 'Person', 'Document', 'Device', 'Bank Account'],
  capability: ['Verification', 'Risk Intelligence', 'Ownership', 'Research', 'Monitoring', 'Policy Review'],
  availability: [
    { id: 'live', label: 'Live data', dot: 'live' },
    { id: 'demo', label: 'Demo data', dot: 'demo' },
    { id: 'external', label: 'External experience', dot: 'external' },
  ],
};
